# Generated by Django 3.1.2 on 2020-10-11 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='prison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prison_name', models.CharField(max_length=200)),
                ('prison_domain_name', models.CharField(max_length=200)),
                ('prison_BBS', models.CharField(max_length=200)),
                ('prison_area', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['-prison_name'],
            },
        ),
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=2000)),
                ('post_date', models.CharField(max_length=200)),
                ('news_url', models.CharField(max_length=200)),
                ('attach_filename', models.CharField(max_length=200)),
                ('news_detail_text', models.CharField(max_length=2000)),
                ('prison_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.prison')),
            ],
        ),
    ]
