# Generated by Django 3.1.2 on 2020-10-11 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='prison_name',
        ),
        migrations.AddField(
            model_name='news',
            name='prison_related',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='polls.prison'),
        ),
    ]
